# Generated by Django 4.2.1 on 2023-05-19 20:58

import Aplicaciones.Principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.PositiveIntegerField(default=Aplicaciones.Principal.models.numeroRandom, max_length=7, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=30)),
                ('Stock', models.PositiveIntegerField(max_length=8)),
                ('Precio', models.CharField(max_length=10)),
                ('Activo', models.DateField()),
            ],
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios_',
        ),
    ]
