# Generated by Django 4.2.1 on 2023-05-19 21:11

import Aplicaciones.Principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_producto_alter_usuarios_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedore',
            fields=[
                ('Codigo', models.PositiveIntegerField(default=Aplicaciones.Principal.models.numeroRandom, max_length=7, primary_key=True, serialize=False)),
                ('Proveedor', models.CharField(max_length=8)),
                ('Correo', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=40)),
                ('Telefono', models.PositiveIntegerField()),
                ('Activo', models.DateField()),
            ],
        ),
    ]
