# Generated by Django 4.2.1 on 2023-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_proveedore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedore',
            name='Proveedor',
            field=models.CharField(max_length=30),
        ),
    ]
