# Generated by Django 4.2.1 on 2023-05-19 21:23

import Aplicaciones.Principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_alter_proveedore_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='Codigo',
            field=models.PositiveIntegerField(default=Aplicaciones.Principal.models.numeroRandom, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='identificacion',
            field=models.PositiveIntegerField(),
        ),
    ]
