# Generated by Django 4.2.1 on 2023-05-19 21:24

import Aplicaciones.Principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_alter_producto_stock_alter_proveedore_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Codigo',
            field=models.PositiveIntegerField(default=Aplicaciones.Principal.models.numeroRandom, primary_key=True, serialize=False),
        ),
    ]
