# Generated by Django 4.2.1 on 2023-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_usuarios_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
