# Generated by Django 4.2.1 on 2023-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0008_alter_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedore',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
