# Generated by Django 4.2.1 on 2023-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0009_alter_proveedore_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Producto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='Correo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='Direccion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='Proveedor',
            field=models.CharField(max_length=120),
        ),
    ]
