# Generated by Django 4.2.1 on 2023-05-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0010_alter_producto_precio_alter_producto_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
